### ISSUE TITLE
Where is GSN integration workshop?

### ISSUE THREAD

**Issue by alin1popa** [opengsn/ctf-react#11]
Posting here because it's the closest repo to the original workshop.
https://github.com/opengsn/workshop has been deleted or made private. Was it intentional? Is there a replacement available?

**Comment by angelagilhotra** [comment]
finding the same ^

**Comment by forshtat** [comment]
@alin1popa @angelagilhotra our appologies, workshop repo was made private by mistake. 
https://github.com/opengsn/workshop  is public again and uses GSN v3 beta.

For an archived version of tutorial for GSN v2 you can see:
https://github.com/opengsn/workshop2

**Comment by angelagilhotra** [comment]
oh great, thank you so much
