### ISSUE TITLE
Failed to compile. Can't resolve '@ctf/eth'

### ISSUE THREAD

**Issue by prajwolrg** [opengsn/ctf-react#7]
```
./src/components/CaptureTheFlag.tsx
Module not found: Can't resolve '@ctf/eth' in '/home/prajwolrg/School/ctf-react/workspaces/react-app/src/components'

```
To reproduce:
1. Clone https://github.com/opengsn/ctf-react
2. Follow README instructions:
    2.1. yarn install ✅
    2.2. yarn evm-with-gsn ✅
    2.3 yarn deploy ✅
    2.4 yarn start ❌ [Error here]

**Comment by drortirosh** [comment]
strangely, it fails on latest node >= 16
it works well with node 12, 14
